language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

after_script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token=$STOKEN --format=php-clover coverage.clover

script: ./vendor/bin/phpunit --configuration ./phpunit.xml

matrix:
  fast_finish: true
